#!/usr/bin/bash

echo "Installing dependencies..."
sudo apt-get update
sudo apt-get install zsh curl stow git ripgrep vim wget curl git gpg pass build-essential zlib1g zlib1g-dev -y

sudo dnf install \
      gcc gcc-c++ gdb lzma glibc-devel libstdc++-devel openssl-devel \
      readline-devel zlib-devel libzstd-devel libffi-devel bzip2-devel \
      xz-devel sqlite sqlite-devel sqlite-libs libuuid-devel gdbm-libs \
      perf expat expat-devel mpdecimal python3-pip -y
