#!/usr/bin/bash

echo "Installing dependencies..."
sudo apt-get update
sudo apt-get install zsh curl stow git ripgrep vim wget curl git gpg pass build-essential zlib1g zlib1g-dev -y

sudo apt-get install build-essential gdb lcov pkg-config \
      libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
      libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
      lzma lzma-dev tk-dev uuid-dev zlib1g-dev libzstd-dev -y
