#!/usr/bin/bash

echo "Installing dependencies..."
sudo yum update -y
sudo yum install zsh curl stow git ripgrep vim wget gpg pass gcc gcc-c++ make zlib zlib-devel -y

sudo yum install gcc gcc-c++ gdb lcov pkgconfig \
      bzip2-devel libffi-devel gdbm-devel xz-devel \
      ncurses-devel readline-devel sqlite-devel openssl-devel \
      xz tk-devel libuuid-devel zlib-devel libzstd-devel -y
