#!/usr/bin/env zsh

# Only include packages that actually exist
my_array=("bin" "nvim" "tmux" "zsh")

for item in "${my_array[@]}"; do
	if [[ -d "$item" ]]; then
		echo "Removing $item"
		stow -D "$item" -t "$HOME"
	else
		echo "Skipping $item (directory not found)"
	fi
done
