#!/bin/bash
echo "Installing asdf"
brew install asdf
asdf --version

asdf plugin add python https://github.com/asdf-community/asdf-python.git
asdf plugin add dotnet https://github.com/hensou/asdf-dotnet.git
asdf plugin-add terraform https://github.com/asdf-community/asdf-hashicorp.git
asdf plugin add poetry https://github.com/asdf-community/asdf-poetry.git
asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf plugin add neovim
