#!/usr/bin/env sh

# Enable tiling
yabai -m config layout bsp

# Nice gaps & padding
yabai -m config window_gap          6
yabai -m config top_padding         10
yabai -m config bottom_padding      10
yabai -m config left_padding        10
yabai -m config right_padding       10

# Float annoying apps
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Finder" manage=off
