-- vim.opt.clipboard = "unnamedplus"
--
-- if os.getenv("TMUX") then
--   vim.g.clipboard = {
--     name = "tmux",
--     copy = {
--       ["+"] = "tmux load-buffer -",
--       ["*"] = "tmux load-buffer -",
--     },
--     paste = {
--       ["+"] = "tmux save-buffer -p",
--       ["*"] = "tmux save-buffer -p",
--     },
--   }
-- end
